/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ShowcaseIndexImport } from './routes/showcase/index'
import { Route as PackagesIndexImport } from './routes/packages/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ShowcaseIndexRoute = ShowcaseIndexImport.update({
  id: '/showcase/',
  path: '/showcase/',
  getParentRoute: () => rootRoute,
} as any)

const PackagesIndexRoute = PackagesIndexImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesIndexImport
      parentRoute: typeof rootRoute
    }
    '/showcase/': {
      id: '/showcase/'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/packages': typeof PackagesIndexRoute
  '/showcase': typeof ShowcaseIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/packages': typeof PackagesIndexRoute
  '/showcase': typeof ShowcaseIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/showcase/': typeof ShowcaseIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/packages' | '/showcase'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/packages' | '/showcase'
  id: '__root__' | '/' | '/packages/' | '/showcase/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
  ShowcaseIndexRoute: typeof ShowcaseIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PackagesIndexRoute: PackagesIndexRoute,
  ShowcaseIndexRoute: ShowcaseIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/packages/",
        "/showcase/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/packages/": {
      "filePath": "packages/index.tsx"
    },
    "/showcase/": {
      "filePath": "showcase/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
