import { defineSlotRecipe } from "@pandacss/dev";

export const sidebar = defineSlotRecipe({
    className: "sidebar",
    slots: [
        "root",
        "header",
        "content",
        "footer",
        "section",
        "sectionHeader",
        "sectionLabel",
        "sectionContent",
        "menu",
        "menuItem",
    ],
    jsx: ["Sidebar", "SidebarRoot"],
    base: {
        root: {
            width: "64",
            height: "viewportHeight",
            flexShrink: "0",
            display: "flex",
            flexDirection: "column",
            position: "sticky",
            top: "0",
            left: "0",

            backgroundColor: "panel",
            borderRight: "default",
        },
        header: {
            padding: "2",
            width: "full",
            flexShrink: "0",
            display: "flex",
            flexDirection: "column",
            gap: "2",
        },
        content: {
            width: "full",
            minHeight: "0",
            flexGrow: "1",
            display: "flex",
            flexDirection: "column",
            overflowY: "auto",
            position: "relative",
        },
        footer: {
            padding: "2",
            width: "full",
            flexShrink: "0",
            display: "flex",
            flexDirection: "column",
            gap: "2",
        },
        section: {
            position: "relative",
            width: "full",
            minWidth: "0",
            display: "flex",
            flexDirection: "column",
            padding: "2",
        },
        sectionHeader: {
            height: "8",
            paddingX: "2",
            flexShrink: "0",
            display: "flex",
            alignItems: "center",
        },
        sectionLabel: {
            fontFamily: "sans",
            fontWeight: "medium",
            textStyle: "xs",
            color: "neutral.11",
        },
        sectionContent: {
            width: "full",
            position: "relative",
            textStyle: "sm",
        },
        menu: {
            width: "full",
            minWidth: "0",
            display: "flex",
            flexDirection: "column",
            gap: "1",
        },
        menuItem: {
            position: "relative",
            flexShrink: "0",
            paddingX: "2",
            paddingY: "1.5",
            gap: "2",
            borderRadius: "md",
            userSelect: "none",
            display: "flex",
            alignItems: "center",
            fontFamily: "sans",
            fontWeight: "medium",
            textStyle: "sm",
            truncate: true,

            color: "neutral.12",
            backgroundColor: "transparent",
            _hover: {
                backgroundColor: "neutral.a3",
            },
            _active: {
                backgroundColor: "neutral.a4",
            },

            "& :where(svg)": {
                fontSize: "md",
                opacity: "0.9",
            },
        },
    },
});
