name: CI

on:
    pull_request:
    push:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    commitlint:
        name: Check Commit Messages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Cache turbo build setup
              uses: actions/cache@v4
              with:
                  path: .turbo
                  key: ${{ runner.os }}-turbo-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-turbo-

            - name: Install dependencies
              uses: ./.github/composite-actions/install

            - name: Validate current commit (last commit) with commitlint
              if: github.event_name == 'push'
              run: pnpm commitlint --last --verbose

            - name: Validate PR commits with commitlint
              if: github.event_name == 'pull_request'
              run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
    check-code-style:
        name: Check Code Style
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Cache turbo build setup
              uses: actions/cache@v4
              with:
                  path: .turbo
                  key: ${{ runner.os }}-turbo-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-turbo-

            - name: Install dependencies
              uses: ./.github/composite-actions/install

            - name: Build packages
              run: pnpm build

            - name: Check formatting
              run: pnpm format:check

            - name: Lint
              run: pnpm lint

            - name: Typecheck
              run: pnpm check-types
